Repository Clashman16/Fall-from-Furniture, pull requests merged in 2025-08, with the labels that each got.

#9 Animations for Walk, Climb and Fall
  Assets/Resources/Animations/CatAnimator.controller
  Assets/Resources/Animations/CatFall.anim
  Assets/Resources/Animations/CatWalk.anim
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Characters/CatController.cs
  Assets/Scripts/Managers/LevelManager.cs
Labels: 🚀 Feature

#22 Add constraints to slot selection
  Assets/Scripts/UI/DashedLineBorderBehaviour.cs
  Assets/Scripts/UI/FurnitureDropSlotBehaviour.cs
Labels: 🚀 Feature

#35 Implement end menu
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Managers/LevelManager.cs
  Assets/Scripts/UI/Buttons/NextLevelButtonBehaviour.cs
  Assets/Scripts/UI/Buttons/NextLevelButtonBehaviour.cs.meta
  Assets/Scripts/UI/Canvas/EndCanvasBehaviour.cs
  Assets/Scripts/UI/Canvas/GameCanvasBehaviour.cs
  Assets/Scripts/UI/ScreenManagerBehaviour.cs
  Assets/Scripts/UI/TimerBehaviour.cs
Labels: 🚀 Feature

#39 Change fall probability computing
  Assets/Scripts/Utils/FurnitureUtils.cs
Labels: 😈 Bug P0

#40 Fix overlap problems
  Assets/Scenes/SampleScene.unity
  ProjectSettings/TagManager.asset
Labels: 🤬 Bug P1

#41 Make furnitures to not leave slots scope
  Assets/Resources/Prefabs/Interactable/DraggableFurniture.prefab
  Assets/Resources/Prefabs/Interactable/FurnitureSlot.prefab
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Managers/LevelManager.cs
  Assets/Scripts/UI/DashedLineBorderBehaviour.cs
Labels: 😈 Bug P0
